name: writey-drawey-site

lambdaUpdateState:
  component: "@serverless/aws-lambda"
  name: writey-drawey-update-game
  inputs:
    description: "post endpoint for updating game state"
    memory: 128
    timeout: 20
    src: ./backend
    handler: index.update
    runtime: nodejs12.x
    region: us-east-1

lambdaGetState:
  component: "@serverless/aws-lambda"
  name: writey-drawey-game-state
  inputs:
    description: "polling endpoint for fetching game state"
    memory: 1024
    timeout: 4
    src: ./backend
    handler: index.get
    runtime: nodejs12.x
    region: us-east-1

lambdaCors:
  component: "@serverless/aws-lambda"
  name: writey-drawey-api-cors
  inputs:
    description: "general purpose CORS endpoint"
    memory: 128
    timeout: 20
    src: ./backend
    handler: index.cors
    runtime: nodejs12.x
    region: us-east-1

gameApiGateway:
  component: "@serverless/aws-api-gateway"
  inputs:
    description: Writey Drawey
    cors: true
    endpoints:
      - path: /api
        method: POST
        function: ${lambdaUpdateState.arn}
      - path: /state
        method: GET
        function: ${lambdaGetState.arn}
      - path: /api
        method: OPTIONS
        function: ${lambdaCors.arn}
