name: archive

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  run_archive:
    name: Run Archive
    steps:
    - name: Exec
      with:
        node-version: '15.x'
      env:
        AWS_ID: ${{ secrets.AWS_ID }}
        AWS_KEY: ${{ secrets.AWS_KEY }}
        AWS_REG: ${{ secrets.AWS_REG }}
        node_env: ${{ secrets.node_env }}
      run: node backend/archive/exec.js